# Create the required Tables in Hive including the partiotioned table (partitioned by state)

USE guviHive;                                                                                                                                                                                                      
                                                                                                                                                                                                                   
                                                                                                                                                                                                                   
CREATE TABLE IF NOT EXISTS guviHive.pop_estimate_us_2010_2020                                                                                                                                                      
                                                                                                                                                                                                                   
(                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
    SUMLEV INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    STATE INT,                                                                                                                                                                                                     
                                                                                                                                                                                                                   
    COUNTY INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    PLACE INT,                                                                                                                                                                                                     
                                                                                                                                                                                                                   
    COUSUB INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    CONCIT INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    PRIMGEO_FLAG INT,                                                                                                                                                                                              
                                                                                                                                                                                                                   
    FUNCSTAT STRING,                                                                                                                                                                                               
                                                                                                                                                                                                                   
    NAME STRING,                                                                                                                                                                                                   
                                                                                                                                                                                                                   
    STNAME STRING,                                                                                                                                                                                                 
                                                                                                                                                                                                                   
    CENSUS2010POP BIGINT,                                                                                                                                                                                          
                                                                                                                                                                                                                   
    ESTIMATESBASE2010 BIGINT,                                                                                                                                                                                      
                                                                                                                                                                                                                   
    POPESTIMATE2010 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2011 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2012 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2013 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2014 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2015 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2016 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2017 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2018 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2019 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE042020 BIGINT,                                                                                                                                                                                      
                                                                                                                                                                                                                   
    POPESTIMATE2020 BIGINT                                                                                                                                                                                         
                                                                                                                                                                                                                   
)                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
ROW FORMAT DELIMITED                                                                                                                                                                                               
                                                                                                                                                                                                                   
FIELDS TERMINATED BY ','                                                                                                                                                                                           
                                                                                                                                                                                                                   
LINES TERMINATED BY '\n'                                                                                                                                                                                           
                                                                                                                                                                                                                   
STORED AS TEXTFILE                                                                                                                                                                                                 
                                                                                                                                                                                                                   
TBLPROPERTIES ('skip.header.line.count'='1');                                                                                                                                                                      
                                                                                                                                                                                                                   
CREATE TABLE IF NOT EXISTS guviHive.partitioned_pop_estimate_us_2010_2020 (                                                                                                                                        
                                                                                                                                                                                                                   
    SUMLEV INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    COUNTY INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    PLACE INT,                                                                                                                                                                                                     
                                                                                                                                                                                                                   
    COUSUB INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    CONCIT INT,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
    PRIMGEO_FLAG INT,                                                                                                                                                                                              
                                                                                                                                                                                                                   
    FUNCSTAT STRING,                                                                                                                                                                                               
                                                                                                                                                                                                                   
    NAME STRING,                                                                                                                                                                                                   
                                                                                                                                                                                                                   
    STNAME STRING,                                                                                                                                                                                                 
                                                                                                                                                                                                                   
    CENSUS2010POP BIGINT,                                                                                                                                                                                          
                                                                                                                                                                                                                   
    ESTIMATESBASE2010 BIGINT,                                                                                                                                                                                      
                                                                                                                                                                                                                   
    POPESTIMATE2010 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2011 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2012 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2013 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2014 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2015 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2016 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2017 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2018 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE2019 BIGINT,                                                                                                                                                                                        
                                                                                                                                                                                                                   
    POPESTIMATE042020 BIGINT,                                                                                                                                                                                      
                                                                                                                                                                                                                   
    POPESTIMATE2020 BIGINT                                                                                                                                                                                         
                                                                                                                                                                                                                   
)                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
PARTITIONED BY (STATE INT)                                                                                                                                                                                         
                                                                                                                                                                                                                   
ROW FORMAT DELIMITED                                                                                                                                                                                               
                                                                                                                                                                                                                   
FIELDS TERMINATED BY ','                                                                                                                                                                                           
                                                                                                                                                                                                                   
LINES TERMINATED BY '\n'                                                                                                                                                                                           
                                                                                                                                                                                                                   
STORED AS TEXTFILE;   
